services:
  whatsapp-api-1:
    build: .
    container_name: whatsapp-api-1
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - PORT=3001
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=1
      - JWT_SECRET=${JWT_SECRET}
      - SECRET_WORD=${SECRET_WORD}
      - PUPPETEER_EXECUTABLE_PATH=${PUPPETEER_EXECUTABLE_PATH}
      - WEBHOOK_URLS=${WEBHOOK_URLS}
    shm_size: '3gb'
    ports:
      - "3001:3001"
    volumes:
      - ./.wwebjs_auth_1:/app/.wwebjs_auth

  # whatsapp-api-2:
  #   build: .
  #   container_name: whatsapp-api-2
  #   restart: unless-stopped
  #   depends_on:
  #     - redis
  #   environment:
  #     - PORT=3002
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - REDIS_DB=2
  #     - JWT_SECRET=${JWT_SECRET}
  #     - SECRET_WORD=${SECRET_WORD}
  #     - PUPPETEER_EXECUTABLE_PATH=${PUPPETEER_EXECUTABLE_PATH}
  #     - WEBHOOK_URLS=${WEBHOOK_URLS}
  #   shm_size: '1.5gb'
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #     - ./.wwebjs_auth_2:/app/.wwebjs_auth

  # whatsapp-api-3:
  #   build: .
  #   container_name: whatsapp-api-3
  #   restart: unless-stopped
  #   depends_on:
  #     - redis
  #   environment:
  #     - PORT=3003
  #     - REDIS_HOST=${REDIS_HOST}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - REDIS_DB=3
  #     - JWT_SECRET=${JWT_SECRET}
  #     - SECRET_WORD=${SECRET_WORD}
  #     - PUPPETEER_EXECUTABLE_PATH=${PUPPETEER_EXECUTABLE_PATH}
  #     - WEBHOOK_URLS=${WEBHOOK_URLS}
  #   shm_size: '1gb'
  #   ports:
  #     - "3003:3003"
  #   volumes:
  #     - ./.wwebjs_auth_3:/app/.wwebjs_auth

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/whatsapp.conf:/etc/nginx/templates/whatsapp.conf.template:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    environment:
      - SERVER_NAME=${SERVER_NAME:-wa.worldcopier-import.com}
      - HTTPS_REDIRECT=${HTTPS_REDIRECT:-}
      - HTTP_PROXY=${HTTP_PROXY:-#}
      - SSL_DISABLED=${SSL_DISABLED:-}
    depends_on:
      - whatsapp-api-1
      # - whatsapp-api-2
      # - whatsapp-api-3

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: /bin/sh -c 'if [ "$$#" -gt 0 ]; then exec certbot "$$@"; else trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done; fi' --
